"""main.py's flow, re-expressed on the MAF graph workflow API (WorkflowBuilder).

============================================================================
DISCLAIMER: THIS FILE WAS GENERATED BY CLAUDE (at the user's explicit request).
It is a learning companion to main.py — the imperative original is left
untouched. Read it critically; don't treat it as your own hand-written work.
Run it the same way as main.py (from inside project/):  uv run workflow_graph.py
============================================================================

Design rationale (why this shape, not a "pure" cycle of agent-nodes):
  Every AgentExecutor owns its OWN session (agent_framework/_workflows/
  _agent_executor.py:177). That makes a multi-turn *conversation* awkward to model
  as a cycle of agent-nodes: two nodes can't share one growing history without
  threading `full_conversation` down every edge and re-feeding it each turn. So
  the interactive front half lives inside ONE custom executor (GatherRequirements)
  that owns the dev session and loops via request_info; the deterministic back
  half (write -> code -> review -> fix) is where real agent-nodes + conditional
  edges + the iteration cap actually pay off. This mirrors the conclusion reached
  for the imperative version: graphs are worst at dynamic, human-driven control
  flow, best at deterministic orchestration.

One real win this shape gives us over main.py: bounded loops.
  WorkflowBuilder(max_iterations=...) caps total supersteps (DEFAULT_MAX_ITERATIONS
  = 100), so the XL<->Amma review loop can't ping-pong forever the way main.py's
  `while True` can. (Caveat: it bounds the WHOLE run, front half included — see
  build_workflow().) Session handling is otherwise the same as main.py: XL and Amma
  each get their own session, and Soham and the Judge still share one.
"""

import asyncio
from pathlib import Path
from typing import Never

from agent_framework import (
    AgentExecutor,
    AgentExecutorRequest,
    AgentExecutorResponse,
    AgentResponseUpdate,
    Case,
    Default,
    Executor,
    InMemoryCheckpointStorage,
    Message,
    WorkflowBuilder,
    WorkflowCheckpoint,
    WorkflowContext,
    WorkflowExecutor,
    WorkflowViz,
    executor,
    handler,
    response_handler,
)

# from agent_framework.exceptions import ChatClientException
from agents import amma_agent, judge_agent, sm_agent, xl_agent
from constants import OUTPUTS_DIR
from models import ProjectDetails, ProjectRequirements, UserPrompt

# from openai import APIConnectionError
from tools import write_to_file
from utils import (
    RandomException,
    answer_pending_requests,
    stream_segment,
    stream_soham,
    throw_random_exception,
)
from workflow_mini import mini_workflow, mini_workflow_seq

# TODO: look into WorkflowEvent - some stuff is already printed in utils.py


# ---------------------------------------------------------------------------
# Front half: interactive requirements gathering (human-in-the-loop)
# ---------------------------------------------------------------------------
# TODO: can this be done thru adding edges etc
class GatherRequirements(Executor):
    """Owns the Soham<->user<->Judge loop, then emits a ProjectDetails downstream.

    NOTE — request_info in the GRAPH API does NOT return inline. Calling
    `await ctx.request_info(...)` does not give back the user's answer; it just
    pauses the run. The answer arrives later in a separate @response_handler
    method (matched by request/response types). So instead of one `while` loop,
    the work is split in two: `run` starts it, and the response_handler runs
    once per answer to continue.
    """

    def __init__(self, sm_agent, judge, sm_session, id: str = "gather_requirements"):
        super().__init__(id=id)
        self._sm_agent = sm_agent
        self._judge = judge
        # Claude: ONE source of truth — the shared dev session. Soham AND the judge
        # both run on it, so every user turn lands in the session as a side effect,
        # exactly like main.py (the judge run is what injects the user's message).
        # Accepted tradeoff, same as main.py: the judge's verdicts pollute Soham's
        # history and the judge re-reads its own past verdicts. The proposal and the
        # PresentProposal announce later read this same, complete session.
        self._session = sm_session

    # SOHAM: in an executor, the function args (_trigger in this case) denote
    # the expected input data type, while the WorkflowContext[_, _] data types
    # denote the send_message and yield_output data types respectively. So in
    # this case, the executor sends message of type ProjectDetails to the next
    # executor in the graph, and yields AgentResponseUpdate or str as workflow
    # output. Every (class-based) executor has ONE HANDLER PER INPUT TYPE,
    # and one response handler per (request type - response type).
    # Source:
    # https://learn.microsoft.com/en-us/agent-framework/workflows/executors?pivots=programming-language-python
    @handler
    async def run(
        self,
        _trigger: str,
        # Claude: could be ProjectDetails instead of Never. An executor can have many
        # handlers (here run + on_human_turn); MAF takes each handler's declared
        # send-type and UNIONs them into one set for the whole executor, and that set
        # is what type-checks its outgoing edges. So on_human_turn declaring
        # ProjectDetails already puts it in the set (making the edge to write_proposal
        # valid) whether or not run also names it. But Never is more accurate: run
        # never calls send_message (only request_info + yields), so it sends nothing.
        ctx: WorkflowContext[Never, AgentResponseUpdate | str],
    ) -> None:
        # System messages stay developer-controlled (never interpolate user input):
        # https://learn.microsoft.com/en-us/agent-framework/agents/safety#keep-system-messages-developer-controlled
        # Claude: stream Soham's greeting out as workflow output FIRST (so it types
        # out live), then pause for the user's answer.
        await stream_soham(
            self._sm_agent,
            Message(
                role="system",
                contents=["Greet the user, and ask him his requirements."],
            ),
            self._session,
            ctx,
        )
        # SOHAM: ctx.request_info is used when asking input from the user.
        # The executor must have a @response_handler method to handle user inputs.
        # Source: https://learn.microsoft.com/en-us/agent-framework/workflows/human-in-the-loop?pivots=programming-language-python
        # Any request_info call has two primary args:
        # request_data: The request that goes to whoever is driving the workflow while
        #   asking for a response from them. We can pass our custom data types and data,
        #   and whoever is receiving the request must process them accordingly. Like in
        #   this case, we send a UserPrompt with kind "requirements" or "confirm", and
        #   the response_handler does the processing based on the kind.
        # response_type: The expected response type from the user. In this particular
        #   case, we expect a ProjectRequirements with a project_idea and an optional
        #   additional_remarks. In this case, we process this multi-field response
        #   ourselves in utils.take_input_from_user function. Earlier, this method used
        #   to just take strings as inputs using python's input() function. Now it
        #   handles both strings and custom pydantic data types.

        await ctx.request_info(
            request_data=UserPrompt(kind="requirements"),
            response_type=ProjectRequirements,
        )

    # TODO: Claude Review: dev-ui can't render a ProjectRequirements form for this
    # executor and falls back to a plain string box. Two reasons:
    #   1) The `response` param below is a union (str | ProjectRequirements). dev-ui
    #      builds its input form from this handler's static signature and only accepts
    #      a SINGLE concrete class as the response type (agent_framework_devui
    #      _utils.py:386 -> isinstance(second_param_type, type) is False for a union),
    #      so it returns None and falls back to {"type": "string"} (_executor.py:1125).
    #   2) Deeper: dev-ui keys the form off (executor_id, request_type) only and never
    #      sees the per-call response_type= we pass. Both the requirements turn and the
    #      confirm turn share request_type=UserPrompt (told apart only by `kind` at
    #      runtime), so one request_type can't map to two response shapes.
    # Fix (only if we want dev-ui to RUN this flow, not just the CLI driver): split
    # UserPrompt into distinct request types (e.g. RequirementsPrompt / ConfirmPrompt)
    # and give each its own single-typed response_handler
    # (on_requirements(..., response: ProjectRequirements, ...) and
    # on_confirm(..., response: str, ...)). Also make the follow-up requirements ask
    # (see the request_info at the bottom of this method) use ProjectRequirements too,
    # so every requirements pause renders the same form. The CLI driver
    # (take_input_from_user reads event.response_type per event) already handles the
    # current union fine, so this restructure is purely for dev-ui.
    @response_handler
    async def on_human_turn(
        self,
        # The "run" handler calls request info with request_data: UserPrompt
        # and response_type: ProjectRequirements. And this method
        # "on_human_turn" calls request info with request_data: UserPrompt and
        # response_type: str. This response_handler handles both of these
        # types of request info. Basically, there should be one response
        # handler to handle each type of request info. The good thing is that
        # MAF throws a warning if this is not implemented
        request: UserPrompt,
        response: str | ProjectRequirements,
        ctx: WorkflowContext[ProjectDetails, AgentResponseUpdate | str],
    ) -> None:

        if isinstance(response, ProjectRequirements):
            user_response = f"Project idea: {response.project_idea}"
            if response.additional_remarks:
                user_response += f" Additional remarks: {response.additional_remarks}"
        else:
            user_response = response

        if request.kind == "confirm" and response.strip().lower() == "y":
            # Proposal generated from the shared session, which by now holds the
            # full conversation — the judge ran on this session every prior turn,
            # so every user turn (including the one that flipped `ready`) is already
            # in it. Same prompt as main.py.
            details = await self._sm_agent.run(
                Message(
                    role="system",
                    contents=[
                        "Generate a project name and a proposal based on your "
                        "discussion. The project name should be in snake_case. "
                        "The proposal contents should be in markdown format."
                    ],
                ),
                session=self._session,
                options={"response_format": ProjectDetails},
            )
            await ctx.send_message(details.value)  # -> write_proposal
            return
        # Improvement over main.py (which discarded a non-"y" answer — its TODO
        # asked for exactly this): treat it as more requirements input below.

        # Requirements turn (or a "no, here's more" confirm answer): run the judge
        # ON THE SESSION so `response` is injected into the shared history (this is
        # how main.py gets every user turn into the session), then either ask again
        # or move to confirmation.
        #
        # Claude NOTE — the EARLIER BUGGY version is kept commented just below as a
        # lesson. It ran the judge STATELESS on a separate `self._transcript`, so user
        # turns were never written into the dev session; and on the turn the judge
        # flipped to `ready` we skipped dev.run(response) too, so that message reached
        # neither. Proposal-gen then ran on a session holding only the greeting and
        # "restated the greeting" (see the requirements_intake_assistant output, whose
        # line 1 was literally the greeting). Running the judge ON the session fixes it.
        #     self._transcript.append(Message(role="user", contents=[response]))
        #     verdict = await self._judge.run(self._transcript)  # stateless: no session=
        verdict = await self._judge.run(user_response, session=self._session)
        ready = bool(verdict.value and verdict.value.ready)

        if ready:
            # Claude: this prompt is a fixed string (not an agent reply), so we just
            # yield it as one output event — it still shows up under "Soham" via
            # stream_segment — then pause for the y/n.
            await ctx.yield_output(
                "Looks like we have everything we need. Should we proceed "
                "with the final proposal? (y/n)"
            )
            await ctx.request_info(UserPrompt(kind="confirm"), str)
            return

        # Claude: stream Soham's follow-up question live, then pause for more input.
        await stream_soham(self._sm_agent, user_response, self._session, ctx)
        await ctx.request_info(UserPrompt(kind="requirements"), str)


# ---------------------------------------------------------------------------
# Back half: deterministic transforms + real agent nodes
# ---------------------------------------------------------------------------
@executor(id="write_proposal")
async def write_proposal(
    details: ProjectDetails, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    # We write proposal.md ourselves (deterministic) instead of letting an agent
    # do it — same reasoning as main.py. write_to_file is a @tool but stays
    # directly callable.
    project_path = OUTPUTS_DIR / details.project_name
    proposal_file_path = write_to_file(
        filename="proposal.md", contents=details.proposal, filepath=project_path
    )
    # Stash the dynamic paths in the SHARED workflow state (one State per run) so
    # the review / fix / finalize steps downstream can read them.
    ctx.set_state("project_path", str(project_path))
    ctx.set_state("proposal_file_path", str(proposal_file_path))

    # SOHAM: ctx.send_message is used to send messages to the next
    # agent/executor in the graph.
    await ctx.send_message(
        # SOHAM: AgentExecutorRequest is nothing but a series of messages/conversation
        # that is to be passed to the next agent in the workflow.
        # Source: https://github.com/microsoft/agent-framework/blob/main/python/samples/03-workflows/agents/azure_chat_agents_and_executor.py
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        f"Read the contents of this proposal: {proposal_file_path} "
                        f"and code a working solution at {project_path / 'out'} "
                        "directory. IMPORTANT: All project related files (source "
                        "code, readme etc.) should be mandatorily inside the 'out' "
                        "directory. Once you are done coding, inform the user and "
                        "give him the path where your code is."
                    ],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="ask_agent_to_review")
async def ask_agent_to_review(
    _coded: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    throw_random_exception()
    # XL's reply is irrelevant to Amma — Amma reviews the directory on disk.
    # So we discard the coding response and emit a fresh review request.
    out_dir = Path(ctx.get_state("project_path")) / "out"
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[f"Review the code under directory: {out_dir}"],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="ask_agent_to_fix")
async def ask_agent_to_fix(
    review: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    comments = review.agent_response.value.comments
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        "Code review has flagged the following issues: "
                        + comments
                        + " Fix them. If needed, make sure you read existing code "
                        + "to verify correctness before writing your fixes."
                    ],
                )
            ],
            should_respond=True,
        )
    )


# TODO: Claude Review: this returns True (-> handover -> mini_workflow) on a FAILED
# review too, because `not verdict.success` and `verdict is None` count as "stop".
# That was harmless when the True branch went to the old `done` no-op sink, but now it
# markets an unreviewed product. To route ONLY genuine passes onward, gate handover on
# `verdict is not None and verdict.success and verdict.lgtm`, and send failures
# somewhere else.
def review_passed(review: AgentExecutorResponse) -> bool:
    """Edge condition: stop the XL<->Amma loop when the review is done.

    NOTE — conditions receive exactly what the upstream node sent; here that is
    Amma's AgentExecutorResponse, and `.agent_response.value` is the already-parsed
    CodeReviewOutput (Amma has response_format baked in). Unlike main.py — which
    raised on a missing value and would otherwise spin forever — we treat "no
    value" as a stop, so a flaky review ends the loop instead of looping. The
    framework deliberately does NOT swallow exceptions in conditions (_edge.py), so
    keep this total and side-effect free.
    """
    verdict = review.agent_response.value
    return verdict is None or verdict.lgtm or not verdict.success


class PresentProposal(Executor):
    """Soham announces the proposal and promises the product BEFORE coding starts.

    Claude: positioned between write_proposal and xl so the "you'll have a finished
    product shortly" message lands in the same place main.py emits it (before XL
    codes), NOT after the review. It also forwards XL's coding request downstream.
    Reuses the dev session so the summary has full conversational context.
    """

    def __init__(self, sm_agent, sm_session, id: str = "present_proposal"):
        super().__init__(id=id)
        self._sm_agent = sm_agent
        self._session = sm_session

    @handler
    async def run(
        self,
        xl_request: AgentExecutorRequest,
        ctx: WorkflowContext[AgentExecutorRequest, str],
    ) -> None:
        proposal_file_path = ctx.get_state("proposal_file_path")
        # Claude: stream the summary so it types out live under "Soham" (executor_id
        # "present_proposal"); stream_soham yields one update per chunk.
        await stream_soham(
            self._sm_agent,
            Message(
                role="system",
                contents=[
                    "Summarize the discussion, tell the user that the proposal "
                    f"file is present at {proposal_file_path}, give him the name, "
                    "and tell him he will have a finished product shortly. DO NOT "
                    "ask any questions at this stage, as this is supposed to be the "
                    "final approach."
                ],
            ),
            self._session,
            ctx,
        )
        await ctx.send_message(xl_request)  # -> xl starts coding


@executor(id="handover_to_mini_workflow")
async def handover(review: AgentExecutorResponse, ctx: WorkflowContext[str]):
    # TODO: Claude Review: review_path is None when value is None (a failed review that
    # review_passed still routed here), so the message becomes "Files present under
    # None" and Summarizer reads a bogus path. Fixing the review_passed routing above
    # makes this branch unreachable with a None value.
    review_path = (
        review.agent_response.value.review_path if review.agent_response.value else None
    )
    # Other executors in this project send an AgentExecutorRequest in send_message, this
    # one sends a simple string. This is because AgentExecutorRequest was failing when
    # trying with sequential workflow.
    await ctx.send_message(f"Files present under {review_path}")


# Claude: a stable name so checkpoints can be listed back by workflow_name. Without
# a name, WorkflowBuilder auto-generates one per build, which we'd then have to read
# off the built workflow — a fixed literal keeps list/get_latest calls simple.
WORKFLOW_NAME = "aistudio_dev_workflow"


def build_workflow(checkpoint_storage=None):
    # ONE dev session, shared by the gatherer and the presenter so Soham keeps full
    # conversational memory end to end. XL and Amma get their own isolated sessions
    # (created internally by AgentExecutor).
    sm_session = sm_agent.create_session()
    gather_requirements = GatherRequirements(sm_agent, judge_agent, sm_session)
    present_proposal = PresentProposal(sm_agent, sm_session)
    xl = AgentExecutor(xl_agent, id="xl")
    amma = AgentExecutor(amma_agent, id="amma")
    mini_workflow_exec = WorkflowExecutor(
        mini_workflow,
        id="mini_workflow",
        propagate_request=True,
        allow_direct_output=True,
    )

    # NOTE — max_iterations is the safety cap main.py's `while True` lacks, but it
    # bounds the WHOLE run (every superstep, conversation included), not just the
    # review loop. Default is 100; a very long Q&A could approach it.
    return (
        # Claude: passing checkpoint_storage is what turns checkpointing ON — with it
        # None, every create_checkpoint call is a no-op (_runner.py:214). name lets us
        # list the saved checkpoints back out afterwards.
        WorkflowBuilder(
            start_executor=gather_requirements,
            max_iterations=100,
            name=WORKFLOW_NAME,
            checkpoint_storage=checkpoint_storage,
        )
        .add_edge(gather_requirements, write_proposal)
        # Soham announces the proposal (product-shortly message) BEFORE XL codes.
        .add_edge(write_proposal, present_proposal)
        .add_edge(present_proposal, xl)
        .add_edge(xl, ask_agent_to_review)
        .add_edge(ask_agent_to_review, amma)
        # Switch-case = exactly-one routing (vs. add_edge conditions, where every
        # matching edge fires). Done -> done sink; otherwise -> fix, then loop to XL.
        .add_switch_case_edge_group(
            amma,
            [
                Case(condition=review_passed, target=handover),
                Default(target=ask_agent_to_fix),
            ],
        )
        .add_edge(ask_agent_to_fix, xl)
        .add_edge(handover, mini_workflow_exec)
        .build()
    )


# SOHAM: Earlier, these were in main(). It was moved out just because devui needs
# workflows to be at the module level to be able to detect them.
# Claude: in-memory store — checkpoints live only for this process run. Item 2 of
# the checkpointing TODO (persist to disk/db) would swap this for
# FileCheckpointStorage or a custom CheckpointStorage. Passing it into
# build_workflow is what enables saving.
checkpoint_storage = InMemoryCheckpointStorage()
workflow = build_workflow(checkpoint_storage)


# Claude: commented out — auto resume-from-checkpoint disabled for now.
# async def _run_with_resume(
#     workflow, checkpoint_storage, *, max_attempts: int = 3, **run_kwargs
# ):
#     """Run (or resume) the workflow, recovering a transient chat-client failure by
#     resuming from the last saved checkpoint instead of restarting the whole run.
#
#     Claude: the graph runner re-raises an agent's exception (_runner.py:122-130), so a
#     single API timeout aborts the entire run. But a checkpoint is saved after every
#     completed superstep, so on failure we resume from the newest one — the failed
#     superstep re-runs and the conversation so far is NOT re-asked. Bounded by
#     max_attempts so a genuinely-down endpoint doesn't loop forever.
#
#     Caveat: our checkpoints live in InMemoryCheckpointStorage, so this only recovers a
#     failure we catch WITHOUT the process exiting — a full crash loses them. Switch to
#     FileCheckpointStorage (checkpointing TODO item 2) to survive a restart.
#     """
#     for attempt in range(1, max_attempts + 1):
#         try:
#             return await stream_segment(
#                 workflow.run(stream=True, **run_kwargs), checkpoint_storage
#             )
#         except ChatClientException as exc:
#             # Claude: only RESUME transient network failures (connect drops + timeouts).
#             # The wrapper is raised `from ex` (_chat_completion_client.py:538,546), so
#             # the original openai error is on exc.__cause__. APITimeoutError is a
#             # subclass of APIConnectionError, so this one check covers both. A permanent
#             #  error (bad request, bad key) would just fail again, so we re-raise it now
#             # instead of burning attempts.
#             if not isinstance(exc.__cause__, APIConnectionError):
#                 raise
#             latest = await checkpoint_storage.get_latest(workflow_name=WORKFLOW_NAME)
#             if latest is None or attempt == max_attempts:
#                 raise
#             print(
#                 f"\n[RESUME] {type(exc).__name__} on attempt {attempt}/{max_attempts}"
#                 f"; resuming from checkpoint {latest.checkpoint_id}"
#             )
#             # Claude: after the first failure we RESUME the saved run — drop the
#             # original message/responses and continue from the checkpoint instead.
#             run_kwargs = {
#                 "checkpoint_id": latest.checkpoint_id,
#                 "checkpoint_storage": checkpoint_storage,
#             }


async def main():
    # To save workflow visualization in a pdf
    viz = WorkflowViz(workflow)
    print(viz.save_pdf("workflow.pdf"))

    # NOTE — this driver loop is the imperative shell the workflow can't absorb:
    # run -> collect pending human/approval requests -> answer -> resume. The
    # `responses=` kwarg is how you feed answers back in (_workflow.py:519). The run
    # is done when a resume returns with no more pending requests.
    # Claude: stream=True makes run() return a ResponseStream we iterate live, so
    # every agent (Soham, XL, Amma) types out its reply instead of dumping it in one
    # block. The run -> answer -> resume loop is otherwise identical; stream_segment
    # renders the events and hands back the WorkflowRunResult so we can still read
    # its pending requests.

    responses = None
    checkpoint_to_resume: WorkflowCheckpoint | None = None

    while True:
        try:
            if checkpoint_to_resume:
                # Soham: Earlier, this was in the except clause. But, the exception can
                # occur anytime inside the workflow.run itself. In case the exception
                # occurred inside the except clause, there was no guard.
                # So moved it here.
                # Resuming vs rehydrating checkpoints:
                # Instead of resuming the same workflow instance from a saved
                # checkpoint, we can even use that checkpoint in an entirely new
                # workflow instance.
                # Refer: https://learn.microsoft.com/en-us/agent-framework/workflows/checkpoints?tabs=py-ckpt-inmemory&pivots=programming-language-python#rehydrating-from-checkpoints
                result = await stream_segment(
                    workflow.run(
                        checkpoint_id=checkpoint_to_resume.checkpoint_id, stream=True
                    ),
                    WORKFLOW_NAME,
                    checkpoint_storage,
                )
                checkpoint_to_resume = None
            elif responses:
                result = await stream_segment(
                    workflow.run(responses=responses, stream=True),
                    WORKFLOW_NAME,
                    checkpoint_storage,
                )
                responses = None
            else:
                # SOHAM: workflow.run always needs an input to run. So we give this
                # message: start.
                # If we try workflow.run() without any input:
                # ValueError: Must provide at least one of: 'message' (new run),
                # 'responses' (send responses), or 'checkpoint_id'
                # (resume from checkpoint).
                result = await stream_segment(
                    workflow.run(message="start", stream=True),
                    WORKFLOW_NAME,
                    checkpoint_storage,
                )

            # SOHAM: result.get_request_info_events() is basically the workflow
            # equivalent of result.user_input_requests which we get while calling
            # standalone agents (or chunk.user_input_requests in case of streaming).
            requests = result.get_request_info_events()
            if not requests:
                break
            responses = await answer_pending_requests(requests)

        except RandomException:
            print("RANDOM EXCEPTION OCCURRED!")
            # Claude: a failure invalidates any in-flight responses (their pending
            # request was already consumed by the failed run). Clear them AND resume
            # from the last checkpoint, which the branch order above prioritises.
            checkpoint_to_resume = await checkpoint_storage.get_latest(
                workflow_name=workflow.name
            )
            responses = None

            if checkpoint_to_resume:
                print(
                    f"RESTARTING FROM CHECKPOINT: {checkpoint_to_resume.checkpoint_id}"
                )
            else:
                print("No checkpoint found to resume from, starting again..")


if __name__ == "__main__":
    asyncio.run(main())


# TODO: next up - checkpointing
# 1. print checkpoints (done)
# 2. try somehow interrupting and resuming from a checkpoint - save the checkpoint,
# raise an exception manually on random choice and resume workflow using that checkpoint
# id. (done)
# 3. store checkpoints somewhere (preferably db but what are the other
# providers?) and inspect them.
# 4. Check out BS's repo. it doesn't have an outright checkpoint provider. So how is it
# handled there? Current version has a single agent - but what about the orchestrator
# version?
# TODO: print all llm calls
