"""main.py's flow, re-expressed on the MAF graph workflow API (WorkflowBuilder).

============================================================================
DISCLAIMER: THIS FILE WAS GENERATED BY CLAUDE (at the user's explicit request).
It is a learning companion to main.py — the imperative original is left
untouched. Read it critically; don't treat it as your own hand-written work.
Run it the same way as main.py (from inside project/):  uv run workflow_graph.py
============================================================================

Design rationale (why this shape, not a "pure" cycle of agent-nodes):
  Every AgentExecutor owns its OWN session (agent_framework/_workflows/
  _agent_executor.py:177). That makes a multi-turn *conversation* awkward to model
  as a cycle of agent-nodes: two nodes can't share one growing history without
  threading `full_conversation` down every edge and re-feeding it each turn. So
  the interactive front half lives inside ONE custom executor (GatherRequirements)
  that owns the dev session and loops via request_info; the deterministic back
  half (write -> code -> review -> fix) is where real agent-nodes + conditional
  edges + the iteration cap actually pay off. This mirrors the conclusion reached
  for the imperative version: graphs are worst at dynamic, human-driven control
  flow, best at deterministic orchestration.

Two wins this gives us over main.py for free:
  1. No session pollution. main.py shares ONE session between Soham and the Judge,
     so the Judge's verdicts leak into Soham's history. Here the Judge runs
     STATELESS on its own transcript (see GatherRequirements), and every
     AgentExecutor node has its own isolated session.
  2. Bounded loops. WorkflowBuilder(max_iterations=...) caps total supersteps
     (DEFAULT_MAX_ITERATIONS = 100), so the XL<->Amma review loop can't ping-pong
     forever the way main.py's `while True` can. (Caveat: it bounds the WHOLE run,
     front half included — see build_workflow().)
"""

import asyncio
import random
import sys
from pathlib import Path
from typing import Literal, Never

from agent_framework import (
    Agent,
    AgentExecutor,
    AgentExecutorRequest,
    AgentExecutorResponse,
    AgentResponseUpdate,
    AgentSession,
    Case,
    Default,
    Executor,
    InMemoryCheckpointStorage,
    Message,
    WorkflowBuilder,
    WorkflowCheckpoint,
    WorkflowContext,
    # WorkflowViz,
    executor,
    handler,
    response_handler,
)

# from agent_framework.exceptions import ChatClientException
from agents import amma_agent, judge_agent, sm_agent, xl_agent
from constants import OUTPUTS_DIR
from models import ProjectDetails

# from openai import APIConnectionError
from pydantic import BaseModel
from tools import write_to_file

# TODO: look into WorkflowEvent


# The payload we hand the driver whenever we need a human turn. It carries only
# `kind` so the ONE response_handler below can tell a requirements answer apart
# from a yes/no confirmation.
# Claude: the prompt TEXT used to live here (the driver printed it). It doesn't
# anymore — Soham's words are now streamed live as workflow output (see
# _stream_soham), so the driver just needs to know a human turn is pending and how
# to route the answer.
# SOHAM: This can be either dataclass or pydantic model.
class UserPrompt(BaseModel):
    kind: Literal["requirements", "confirm"]


class ProjectRequirements(BaseModel):
    project_idea: str
    additional_remarks: str = ""


class RandomException(Exception):
    pass


def throw_random_exception():
    # SOHAM: throw an exception 1/3rd of the time, to test checkpointing
    rand_int = random.choice([1, 2, 3])
    if rand_int == 3:
        raise RandomException


async def _stream_soham(
    agent: Agent, message: str | Message, session: AgentSession, ctx
) -> None:
    """Run Soham with streaming and surface each chunk as workflow output.

    Claude: yielding the updates (instead of running non-streamed and yielding one
    final string) is what makes his words type out live via _stream_segment, under
    his "Soham" label. Iterating the stream to the end also finalizes the run and
    writes it into the shared session — ResponseStream calls get_final_response()
    on exhaustion (_types.py:3117-3120) — so his conversation memory stays intact.

    Claude: contrast with the earlier NON-streaming version — there Soham's text
    rode inside the UserPrompt and reached the driver as part of the request_info
    event (the driver printed `prompt.text` before reading input); it was never a
    yield_output. Streaming flips that: the text goes out via yield_output here, and
    request_info now carries only the routing `kind`.
    """
    # TODO: explain why it was kept here instead of main
    throw_random_exception()
    async for update in agent.run(message, session=session, stream=True):
        # SOHAM: ctx.yield_output yields the outputs of the workflow which the user
        # sees. If agents/agentexecutors are present in the workflow, all of their
        # outputs are yielded by default, unless output_from is set.
        await ctx.yield_output(update)


# ---------------------------------------------------------------------------
# Front half: interactive requirements gathering (human-in-the-loop)
# ---------------------------------------------------------------------------
# TODO: can this be done thru adding edges etc
class GatherRequirements(Executor):
    """Owns the Soham<->user<->Judge loop, then emits a ProjectDetails downstream.

    NOTE — request_info in the GRAPH API does NOT return inline. Calling
    `await ctx.request_info(...)` does not give back the user's answer; it just
    pauses the run. The answer arrives later in a separate @response_handler
    method (matched by request/response types). So instead of one `while` loop,
    the work is split in two: `run` starts it, and the response_handler runs
    once per answer to continue.
    """

    def __init__(self, sm_agent, judge, sm_session, id: str = "gather_requirements"):
        super().__init__(id=id)
        self._sm_agent = sm_agent
        self._judge = judge
        # Claude: ONE source of truth — the shared dev session. Soham AND the judge
        # both run on it, so every user turn lands in the session as a side effect,
        # exactly like main.py (the judge run is what injects the user's message).
        # Accepted tradeoff, same as main.py: the judge's verdicts pollute Soham's
        # history and the judge re-reads its own past verdicts. The proposal and the
        # PresentProposal announce later read this same, complete session.
        self._session = sm_session

    # SOHAM: in an executor, the function args (_trigger in this case) denote
    # the expected input data type, while the WorkflowContext[_, _] data types
    # denote the send_message and yield_output data types respectively. So in
    # this case, the executor sends message of type ProjectDetails to the next
    # executor in the graph, and yields AgentResponseUpdate or str as workflow
    # output. Every (class-based) executor has ONE HANDLER PER INPUT TYPE,
    # and one response handler per (request type - response type).
    # Source:
    # https://learn.microsoft.com/en-us/agent-framework/workflows/executors?pivots=programming-language-python
    @handler
    async def run(
        self,
        _trigger: str,
        # Claude: could be ProjectDetails instead of Never. An executor can have many
        # handlers (here run + on_human_turn); MAF takes each handler's declared
        # send-type and UNIONs them into one set for the whole executor, and that set
        # is what type-checks its outgoing edges. So on_human_turn declaring
        # ProjectDetails already puts it in the set (making the edge to write_proposal
        # valid) whether or not run also names it. But Never is more accurate: run
        # never calls send_message (only request_info + yields), so it sends nothing.
        ctx: WorkflowContext[Never, AgentResponseUpdate | str],
    ) -> None:
        # System messages stay developer-controlled (never interpolate user input):
        # https://learn.microsoft.com/en-us/agent-framework/agents/safety#keep-system-messages-developer-controlled
        # Claude: stream Soham's greeting out as workflow output FIRST (so it types
        # out live), then pause for the user's answer.
        await _stream_soham(
            self._sm_agent,
            Message(
                role="system",
                contents=["Greet the user, and ask him his requirements."],
            ),
            self._session,
            ctx,
        )
        # SOHAM: ctx.request_info is used when asking input from the user.
        # The executor must have a @response_handler method to handle user inputs.
        # Source: https://learn.microsoft.com/en-us/agent-framework/workflows/human-in-the-loop?pivots=programming-language-python
        # TODO: need some more clarity on request_data
        await ctx.request_info(
            request_data=UserPrompt(kind="requirements"),
            response_type=ProjectRequirements,
        )

    @response_handler
    async def on_human_turn(
        self,
        # The "run" handler calls request info with request_data: UserPrompt
        # and response_type: ProjectRequirements. And this method
        # "on_human_turn" calls request info with request_data: UserPrompt and
        # response_type: str. This response_handler handles both of these
        # types of request info. Basically, there should be one response
        # handler to handle each type of request info. The good thing is that
        # MAF throws a warning if this is not implemented
        request: UserPrompt,
        response: str | ProjectRequirements,
        ctx: WorkflowContext[ProjectDetails, AgentResponseUpdate | str],
    ) -> None:

        if isinstance(response, ProjectRequirements):
            user_response = f"Project idea: {response.project_idea}"
            if response.additional_remarks:
                user_response += f" Additional remarks: {response.additional_remarks}"
        else:
            user_response = response

        if request.kind == "confirm" and response.strip().lower() == "y":
            # Proposal generated from the shared session, which by now holds the
            # full conversation — the judge below runs on the session too, so
            # every user turn (including the one that flips `ready`) is already
            # in it. Same prompt as main.py.
            details = await self._sm_agent.run(
                Message(
                    role="system",
                    contents=[
                        "Generate a project name and a proposal based on your "
                        "discussion. The project name should be in snake_case. "
                        "The proposal contents should be in markdown format."
                    ],
                ),
                session=self._session,
                options={"response_format": ProjectDetails},
            )
            await ctx.send_message(details.value)  # -> write_proposal
            return
        # Improvement over main.py (which discarded a non-"y" answer — its TODO
        # asked for exactly this): treat it as more requirements input below.

        # Requirements turn (or a "no, here's more" confirm answer): run the judge
        # ON THE SESSION so `response` is injected into the shared history (this is
        # how main.py gets every user turn into the session), then either ask again
        # or move to confirmation.
        #
        # Claude NOTE — the EARLIER BUGGY version is kept commented just below as a
        # lesson. It ran the judge STATELESS on a separate `self._transcript`, so user
        # turns were never written into the dev session; and on the turn the judge
        # flipped to `ready` we skipped dev.run(response) too, so that message reached
        # neither. Proposal-gen then ran on a session holding only the greeting and
        # "restated the greeting" (see the requirements_intake_assistant output, whose
        # line 1 was literally the greeting). Running the judge ON the session fixes it.
        #     self._transcript.append(Message(role="user", contents=[response]))
        #     verdict = await self._judge.run(self._transcript)  # stateless: no session=
        verdict = await self._judge.run(user_response, session=self._session)
        ready = bool(verdict.value and verdict.value.ready)

        if ready:
            # Claude: this prompt is a fixed string (not an agent reply), so we just
            # yield it as one output event — it still shows up under "Soham" via
            # _stream_segment — then pause for the y/n.
            await ctx.yield_output(
                "Looks like we have everything we need. Should we proceed "
                "with the final proposal? (y/n)"
            )
            await ctx.request_info(UserPrompt(kind="confirm"), str)
            return

        # Claude: stream Soham's follow-up question live, then pause for more input.
        await _stream_soham(self._sm_agent, user_response, self._session, ctx)
        await ctx.request_info(UserPrompt(kind="requirements"), str)


# ---------------------------------------------------------------------------
# Back half: deterministic transforms + real agent nodes
# ---------------------------------------------------------------------------
@executor(id="write_proposal")
async def write_proposal(
    details: ProjectDetails, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    # We write proposal.md ourselves (deterministic) instead of letting an agent
    # do it — same reasoning as main.py. write_to_file is a @tool but stays
    # directly callable.
    project_path = OUTPUTS_DIR / details.project_name
    proposal_file_path = write_to_file(
        filename="proposal.md", contents=details.proposal, filepath=project_path
    )
    # Stash the dynamic paths in the SHARED workflow state (one State per run) so
    # the review / fix / finalize steps downstream can read them.
    ctx.set_state("project_path", str(project_path))
    ctx.set_state("proposal_file_path", str(proposal_file_path))

    # SOHAM: ctx.send_message is used to send messages to the next
    # agent/executor in the graph.
    await ctx.send_message(
        # SOHAM: AgentExecutorRequest is nothing but a series of messages/conversation
        # that is to be passed to the next agent in the workflow.
        # Source: https://github.com/microsoft/agent-framework/blob/main/python/samples/03-workflows/agents/azure_chat_agents_and_executor.py
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        f"Read the contents of this proposal: {proposal_file_path} "
                        f"and code a working solution at {project_path / 'out'} "
                        "directory. IMPORTANT: All project related files (source "
                        "code, readme etc.) should be mandatorily inside the 'out' "
                        "directory. Once you are done coding, inform the user and "
                        "give him the path where your code is."
                    ],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="ask_agent_to_review")
async def ask_agent_to_review(
    _coded: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    throw_random_exception()
    # XL's reply is irrelevant to Amma — Amma reviews the directory on disk.
    # So we discard the coding response and emit a fresh review request.
    out_dir = Path(ctx.get_state("project_path")) / "out"
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[f"Review the code under directory: {out_dir}"],
                )
            ],
            should_respond=True,
        )
    )


@executor(id="ask_agent_to_fix")
async def ask_agent_to_fix(
    review: AgentExecutorResponse, ctx: WorkflowContext[AgentExecutorRequest]
) -> None:
    comments = review.agent_response.value.comments
    await ctx.send_message(
        AgentExecutorRequest(
            messages=[
                Message(
                    role="system",
                    contents=[
                        "Code review has flagged the following issues: "
                        + comments
                        + " Fix them. If needed, make sure you read existing code "
                        + "to verify correctness before writing your fixes."
                    ],
                )
            ],
            should_respond=True,
        )
    )


def review_passed(review: AgentExecutorResponse) -> bool:
    """Edge condition: stop the XL<->Amma loop when the review is done.

    NOTE — conditions receive exactly what the upstream node sent; here that is
    Amma's AgentExecutorResponse, and `.agent_response.value` is the already-parsed
    CodeReviewOutput (Amma has response_format baked in). Unlike main.py — which
    raised on a missing value and would otherwise spin forever — we treat "no
    value" as a stop, so a flaky review ends the loop instead of looping. The
    framework deliberately does NOT swallow exceptions in conditions (_edge.py), so
    keep this total and side-effect free.
    """
    verdict = review.agent_response.value
    return verdict is None or verdict.lgtm or not verdict.success


class PresentProposal(Executor):
    """Soham announces the proposal and promises the product BEFORE coding starts.

    Claude: positioned between write_proposal and xl so the "you'll have a finished
    product shortly" message lands in the same place main.py emits it (before XL
    codes), NOT after the review. It also forwards XL's coding request downstream.
    Reuses the dev session so the summary has full conversational context.
    """

    def __init__(self, sm_agent, sm_session, id: str = "present_proposal"):
        super().__init__(id=id)
        self._sm_agent = sm_agent
        self._session = sm_session

    @handler
    async def run(
        self,
        xl_request: AgentExecutorRequest,
        ctx: WorkflowContext[AgentExecutorRequest, str],
    ) -> None:
        proposal_file_path = ctx.get_state("proposal_file_path")
        # Claude: stream the summary so it types out live under "Soham" (executor_id
        # "present"); _stream_soham yields one update per chunk.
        await _stream_soham(
            self._sm_agent,
            Message(
                role="system",
                contents=[
                    "Summarize the discussion, tell the user that the proposal "
                    f"file is present at {proposal_file_path}, give him the name, "
                    "and tell him he will have a finished product shortly. DO NOT "
                    "ask any questions at this stage, as this is supposed to be the "
                    "final approach."
                ],
            ),
            self._session,
            ctx,
        )
        await ctx.send_message(xl_request)  # -> xl starts coding


@executor(id="done")
async def done(_review: AgentExecutorResponse) -> None:
    # Claude: terminal sink. Matching main.py, there is no extra Soham message after
    # the review — XL already reported where the code is and Amma's review was shown.
    # Receiving Amma's passing response with nothing further sent lets the run go
    # idle, which is how the driver detects completion.
    pass


# Claude: a stable name so checkpoints can be listed back by workflow_name. Without
# a name, WorkflowBuilder auto-generates one per build, which we'd then have to read
# off the built workflow — a fixed literal keeps list/get_latest calls simple.
WORKFLOW_NAME = "aistudio_dev_workflow"


def build_workflow(checkpoint_storage=None):
    # ONE dev session, shared by the gatherer and the presenter so Soham keeps full
    # conversational memory end to end. XL and Amma get their own isolated sessions
    # (created internally by AgentExecutor).
    sm_session = sm_agent.create_session()
    gather_requirements = GatherRequirements(sm_agent, judge_agent, sm_session)
    present_proposal = PresentProposal(sm_agent, sm_session)
    xl = AgentExecutor(xl_agent, id="xl")
    amma = AgentExecutor(amma_agent, id="amma")

    # NOTE — max_iterations is the safety cap main.py's `while True` lacks, but it
    # bounds the WHOLE run (every superstep, conversation included), not just the
    # review loop. Default is 100; a very long Q&A could approach it.
    return (
        # Claude: passing checkpoint_storage is what turns checkpointing ON — with it
        # None, every create_checkpoint call is a no-op (_runner.py:214). name lets us
        # list the saved checkpoints back out afterwards.
        WorkflowBuilder(
            start_executor=gather_requirements,
            max_iterations=100,
            name=WORKFLOW_NAME,
            checkpoint_storage=checkpoint_storage,
        )
        .add_edge(gather_requirements, write_proposal)
        # Soham announces the proposal (product-shortly message) BEFORE XL codes.
        .add_edge(write_proposal, present_proposal)
        .add_edge(present_proposal, xl)
        .add_edge(xl, ask_agent_to_review)
        .add_edge(ask_agent_to_review, amma)
        # Switch-case = exactly-one routing (vs. add_edge conditions, where every
        # matching edge fires). Done -> done sink; otherwise -> fix, then loop to XL.
        .add_switch_case_edge_group(
            amma,
            [
                Case(condition=review_passed, target=done),
                Default(target=ask_agent_to_fix),
            ],
        )
        .add_edge(ask_agent_to_fix, xl)
        .build()
    )


# Claude: map executor ids -> the agent persona behind them, so outputs are
# attributed correctly. Every AgentExecutor yields its OWN reply as workflow
# output, so xl and amma each surface here; without this map the driver would
# mislabel Amma's review as "Soham".
EXECUTOR_LABELS = {
    "gather_requirements": "Soham",
    "present_proposal": "Soham",
    "xl": "XL",
    "amma": "Amma",
}

# Claude: ANSI escape codes — special character sequences the terminal reads as
# "switch style" instead of printing. \033[2m turns on dim (a fainter shade of the
# normal text color), \033[0m switches back to normal. Codes stack with semicolons,
# so \033[2;36m is dim + cyan. Both diagnostic styles stay dim so the agent
# conversation dominates at full brightness; only the hue tells them apart. If your
# terminal doesn't render dim, gray ("\033[90m") is a good substitute.
# Claude: only colorize when stdout is a real terminal — piping the run to a file
# (e.g. `> run.log`) would otherwise litter it with escape codes.
_IS_TTY = sys.stdout.isatty()
EVENT_STYLE = "\033[2m" if _IS_TTY else ""  # dim, no hue
CHECKPOINT_STYLE = "\033[2;36m" if _IS_TTY else ""  # dim cyan
RESET = "\033[0m" if _IS_TTY else ""


def _format_checkpoint(checkpoint) -> str:
    """One-line-ish summary of a WorkflowCheckpoint for live inspection.

    Claude: the full checkpoint holds the whole conversation (checkpoint.messages) and
    all committed shared state (checkpoint.state) — too big to dump every step. We show
    the identity/chain fields plus which executors have in-flight messages and which
    state keys are set. Swap in `checkpoint.to_dict()` if you want to see everything.
    """
    executors_with_msgs = list(checkpoint.messages.keys())
    state_keys = list(checkpoint.state.keys())
    return (
        f"  checkpoint_id : {checkpoint.checkpoint_id}\n"
        f"  previous      : {checkpoint.previous_checkpoint_id}\n"
        f"  iteration     : {checkpoint.iteration_count}\n"
        f"  msgs pending  : {executors_with_msgs}\n"
        f"  state keys    : {state_keys}\n"
        f"  pending reqs  : {list(checkpoint.pending_request_info_events.keys())}"
    )


def _format_event(event) -> str:
    """Compact one-liner describing a workflow event, for learning/inspection.

    Claude: WorkflowEvent packs every possible field onto one class (_events.py:194)
    and only sets the ones that apply to this event's type. So we pull each field and
    include it only when present — that's how one formatter covers all the event kinds
    (started, status, superstep_started/completed, executor_invoked/completed,
    request_info, warning/error). The data payload is kept to a short preview because
    executor_completed carries the executor's sent messages + outputs
    (_executor.py:288-292), which can be large.
    """
    parts = [f"type={event.type}"]
    if event.executor_id is not None:
        parts.append(f"executor={event.executor_id}")
    if event.iteration is not None:
        parts.append(f"superstep={event.iteration}")
    if event.state is not None:
        # Claude: .state is a WorkflowRunState enum (STARTED, IN_PROGRESS, IDLE,
        # IDLE_WITH_PENDING_REQUESTS, ...); .value is its readable string.
        parts.append(f"state={event.state.value}")
    if event.type == "request_info":
        # These are properties that raise off a non-request_info event, so read them
        # only here (guarded by type). They tell us who is waiting on the human.
        parts.append(f"request_id={event.request_id} from={event.source_executor_id}")
    if event.data is not None:
        preview = str(event.data).replace("\n", " ")
        if len(preview) > 80:
            preview = preview[:80] + "…"
        parts.append(f"data={preview}")
    return "[EVENT] " + "  ".join(parts)


async def _stream_segment(stream, checkpoint_storage=None):
    """Render one streaming run's output live, then return its WorkflowRunResult.

    Claude: with stream=True, each AgentExecutor (XL, Amma) — and Soham too, whose
    turns we stream via _stream_soham — sends its reply as a run of 'output' events
    whose data is an AgentResponseUpdate, one small text chunk per event. So we
    print a labeled header the first time a source speaks, then print its chunks
    inline as they arrive (this is the live typing effect).

    Two things to know:
    - A plain-string yield (the fixed y/n confirm prompt) arrives as a SINGLE output
      event rather than a run of chunks, so it prints in one go. We handle both by
      reading .text when present and falling back to str(event.data).
    - We must keep an empty chunk empty (a chunk's .text is "" on some updates).
      Using `chunk or str(...)` would wrongly dump the raw update object for those,
      so we check `is None` instead.
    """
    last_source = None
    async for event in stream:
        # TODO: what is a superstep? is it similar to a "turn"?
        # Claude: log every event except the per-token output/intermediate stream
        # (rendered as live text below; a line per token would shred the typing).
        # Close any half-printed live line first so the diagnostic starts clean.
        if event.type not in ("output", "intermediate"):
            if last_source is not None:
                print()
                last_source = None
            print()
            print(f"{EVENT_STYLE}{_format_event(event)}{RESET}")

        # Claude: a checkpoint is saved just before each superstep_completed event
        # (_runner.py:143-146). The id isn't on the event, so we read the newest one
        # back out of storage here.
        if event.type == "superstep_completed" and checkpoint_storage is not None:
            latest = await checkpoint_storage.get_latest(workflow_name=WORKFLOW_NAME)
            print()
            # Claude: the style stays on across newlines, so one wrap covers the
            # whole multi-line checkpoint block.
            print(f"{CHECKPOINT_STYLE}[CHECKPOINT @ superstep {event.iteration}]")
            print((_format_checkpoint(latest) if latest else "  (none)") + RESET)
            continue
        if event.type != "output":
            continue
        # AgentResponseUpdate has .text (the chunk); a plain-string yield does not.
        chunk = getattr(event.data, "text", None)
        if chunk is None:
            chunk = str(event.data)
        if event.executor_id != last_source:
            label = EXECUTOR_LABELS.get(event.executor_id, event.executor_id)
            print(f"\n[AGENT {label}]: ", end="", flush=True)
            last_source = event.executor_id
        print(chunk, end="", flush=True)
    if last_source is not None:
        print()  # close off the last streamed line
    # The run is finished (idle or paused for input); hand back the full result so
    # the caller can read any pending request_info events.
    return await stream.get_final_response()


async def take_input_from_user(response_type: type = str) -> str | BaseModel:
    """Read the user's answer, shaped to the expected `response_type`.

    Claude: a plain-str request (confirm y/n, XL's approvals) stays one input() line.
    For a Pydantic model (ProjectRequirements) we ask one line per field and build it,
    so it's generic -- add/rename a field and the prompts follow. is_required() is True
    only when a field has no default, so an optional field left blank uses its default.
    """
    if isinstance(response_type, type) and issubclass(response_type, BaseModel):
        values = {}
        for field_name, field in response_type.model_fields.items():
            required = field.is_required()
            suffix = ": " if required else " (optional, Enter to skip): "
            answer = await asyncio.to_thread(input, f"\n[USER] {field_name}{suffix}")
            # Claude: a required field can't be left blank -- keep asking until the
            # user types something. strip() so spaces alone don't count as filled.
            while required and not answer.strip():
                answer = await asyncio.to_thread(
                    input, f"[USER] {field_name} is required{suffix}"
                )
            if answer or required:
                values[field_name] = answer
        return response_type(**values)
    return await asyncio.to_thread(input, "\n[USER]: ")


async def answer_pending_requests(requests) -> dict:
    """Turn the workflow's pending request_info events into a responses dict.

    NOTE — two kinds of request flow through here:
      1. UserPrompt  — our own conversational asks from GatherRequirements.
      2. function-approval requests — auto-surfaced by AgentExecutor when XL calls
         write_to_file (approval_mode="always_require"). The AgentExecutor turns the
         agent's user_input_requests into workflow request_info events, then resumes
         the agent once we answer.
         Claude NOTE — because we now run with stream=True, this conversion happens
         in the STREAMING branch: the approval prompt only shows up AFTER XL's tokens
         finish streaming, not mid-stream (_agent_executor.py:529-543; the
         non-streaming version that did the same is :447-449).
         Either way the `always_require` approval survives the port for free — we
         reuse the same `to_function_approval_response` call main.py used.
    """
    responses = {}
    for event in requests:
        data = event.data
        if isinstance(data, UserPrompt):
            # Claude: nothing to print here anymore — Soham's question already
            # streamed out as workflow output. We just collect the user's answer.
            # Claude: event.response_type is the type passed to ctx.request_info
            # (ProjectRequirements for a requirements turn, str for a confirm) — it
            # rides on the request-info event, so we read it straight off `event`.
            responses[event.request_id] = await take_input_from_user(
                event.response_type
            )
        elif hasattr(data, "to_function_approval_response"):
            print(f"\n{event.source_executor_id} needs approval:")
            print(f" Function: {data.function_call.name}")
            print(f" Arguments: {data.function_call.arguments}")
            print("Enter 'y' or 'n'.")
            approved = (await take_input_from_user()).strip().lower() == "y"
            responses[event.request_id] = data.to_function_approval_response(
                approved=approved
            )
        else:
            raise RuntimeError(f"Unexpected request payload: {type(data)!r}")
    return responses


# Claude: commented out — auto resume-from-checkpoint disabled for now.
# async def _run_with_resume(
#     workflow, checkpoint_storage, *, max_attempts: int = 3, **run_kwargs
# ):
#     """Run (or resume) the workflow, recovering a transient chat-client failure by
#     resuming from the last saved checkpoint instead of restarting the whole run.
#
#     Claude: the graph runner re-raises an agent's exception (_runner.py:122-130), so a
#     single API timeout aborts the entire run. But a checkpoint is saved after every
#     completed superstep, so on failure we resume from the newest one — the failed
#     superstep re-runs and the conversation so far is NOT re-asked. Bounded by
#     max_attempts so a genuinely-down endpoint doesn't loop forever.
#
#     Caveat: our checkpoints live in InMemoryCheckpointStorage, so this only recovers a
#     failure we catch WITHOUT the process exiting — a full crash loses them. Switch to
#     FileCheckpointStorage (checkpointing TODO item 2) to survive a restart.
#     """
#     for attempt in range(1, max_attempts + 1):
#         try:
#             return await _stream_segment(
#                 workflow.run(stream=True, **run_kwargs), checkpoint_storage
#             )
#         except ChatClientException as exc:
#             # Claude: only RESUME transient network failures (connect drops + timeouts).
#             # The wrapper is raised `from ex` (_chat_completion_client.py:538,546), so
#             # the original openai error is on exc.__cause__. APITimeoutError is a
#             # subclass of APIConnectionError, so this one check covers both. A permanent
#             #  error (bad request, bad key) would just fail again, so we re-raise it now
#             # instead of burning attempts.
#             if not isinstance(exc.__cause__, APIConnectionError):
#                 raise
#             latest = await checkpoint_storage.get_latest(workflow_name=WORKFLOW_NAME)
#             if latest is None or attempt == max_attempts:
#                 raise
#             print(
#                 f"\n[RESUME] {type(exc).__name__} on attempt {attempt}/{max_attempts}"
#                 f"; resuming from checkpoint {latest.checkpoint_id}"
#             )
#             # Claude: after the first failure we RESUME the saved run — drop the
#             # original message/responses and continue from the checkpoint instead.
#             run_kwargs = {
#                 "checkpoint_id": latest.checkpoint_id,
#                 "checkpoint_storage": checkpoint_storage,
#             }


async def main():
    # Claude: in-memory store — checkpoints live only for this process run. Item 2 of
    # the checkpointing TODO (persist to disk/db) would swap this for
    # FileCheckpointStorage or a custom CheckpointStorage. Passing it into
    # build_workflow is what enables saving.
    checkpoint_storage = InMemoryCheckpointStorage()
    workflow = build_workflow(checkpoint_storage)

    # # To save workflow visualization in a pdf
    # viz = WorkflowViz(workflow)
    # print(viz.save_pdf("workflow.pdf"))

    # NOTE — this driver loop is the imperative shell the workflow can't absorb:
    # run -> collect pending human/approval requests -> answer -> resume. The
    # `responses=` kwarg is how you feed answers back in (_workflow.py:519). The run
    # is done when a resume returns with no more pending requests.
    # SOHAM: workflow.run always needs an input to run. So we give this message: start.
    # If we try workflow.run() without any input:
    # ValueError: Must provide at least one of: 'message' (new run),
    # 'responses' (send responses), or 'checkpoint_id' (resume from checkpoint).
    # Claude: stream=True makes run() return a ResponseStream we iterate live, so
    # every agent (Soham, XL, Amma) types out its reply instead of dumping it in one
    # block. The run -> answer -> resume loop is otherwise identical; _stream_segment
    # renders the events and hands back the WorkflowRunResult so we can still read
    # its pending requests.

    responses = None
    checkpoint_to_resume: WorkflowCheckpoint | None = None

    while True:
        try:
            if checkpoint_to_resume:
                # TODO: Explain why here and not in except clause
                result = await _stream_segment(
                    workflow.run(
                        checkpoint_id=checkpoint_to_resume.checkpoint_id, stream=True
                    ),
                    checkpoint_storage,
                )
                checkpoint_to_resume = None
            elif responses:
                result = await _stream_segment(
                    workflow.run(responses=responses, stream=True), checkpoint_storage
                )
                responses = None
            else:
                result = await _stream_segment(
                    workflow.run(message="start", stream=True), checkpoint_storage
                )

            # SOHAM: result.get_request_info_events() is basically the workflow
            # equivalent of result.user_input_requests which we get while calling
            # standalone agents (or chunk.user_input_requests in case of streaming).
            requests = result.get_request_info_events()
            if not requests:
                break
            responses = await answer_pending_requests(requests)

        except RandomException:
            print("RANDOM EXCEPTION OCCURRED!")
            # Claude: a failure invalidates any in-flight responses (their pending
            # request was already consumed by the failed run). Clear them AND resume
            # from the last checkpoint, which the branch order above prioritises.
            checkpoint_to_resume = await checkpoint_storage.get_latest(
                workflow_name=workflow.name
            )
            responses = None

            if checkpoint_to_resume:
                print(
                    f"RESTARTING FROM CHECKPOINT: {checkpoint_to_resume.checkpoint_id}"
                )
            else:
                print("No checkpoint found to resume from, starting again..")


if __name__ == "__main__":
    asyncio.run(main())


# TODO: next up - checkpointing
# 1. print checkpoints (done)
# 2. try somehow interrupting and resuming from a checkpoint - save the checkpoint,
# raise an exception manually on random choice and resume workflow using that checkpoint
# id. (done but understand better)
# Resume vs rehydrate checkpoints? refer doc
# 3. store checkpoints somewhere (preferably db but what are the other
# providers?) and inspect them.
# 4. Check out BS's repo. it doesn't have an outright checkpoint provider. So how is it
# handled there? Current version has a single agent - but what about the orchestrator
# version?
# TODO: further research: orchestrators, workflows as elements in a graph
# (workflowexecutor as per claude)
# 1. try to create your own workflow in another file without claude, then use it as an
# executor in this file.
# 2. repeat the same with orchestrator
# TODO: print all llm calls
